steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloudkoel/ceebu-koel', '-f', '.gitpod.dockerfile', '.']
  - name: 'gcr.io/gcp-runtimes/exec-sdk'
    args: ['appcfg', 'update', '--promote', '--version=v1', '--stop_previous_version', 'gcr.io/cloudkoel/ceebu-koel']

